'area: android':
  - changed-files:
      - any-glob-to-any-file: 'crates/glitchpad-host/gen/android/**'
'area: documentation':
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - 'specs/**'
'area: frontend':
  - changed-files:
      - any-glob-to-any-file: 'apps/glitchpad/**'
'area: native':
  - changed-files:
      - any-glob-to-any-file: 'crates/**'
'area: repository':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'scripts/**'
'area: platform/build':
  - changed-files:
      - any-glob-to-any-file:
          - 'packaging/**'
          - 'crates/glitchpad-host/tauri*.json'
          - 'scripts/windows/**'
          - '.github/workflows/windows-package.yml'
