// GENERATED by BrandBuilder gen_egui.py. Idiomatic immediate-mode helpers.
use crate::{CapabilityError, Density, RuntimeCapabilities, ThemeMode};
use crate::tokens::Tokens;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ButtonIntent { Primary, Secondary, Ghost, Destructive }

fn install_style(ctx: &egui::Context, egui_theme: egui::Theme, theme: ThemeMode, density: Density, text_scale: f32) {
    let tokens = Tokens::for_theme(theme, density);
    let mut style = egui_theme.default_style();
    style.spacing.item_spacing = egui::vec2(tokens.spacing_control, tokens.spacing_control);
    style.spacing.button_padding = egui::vec2(tokens.spacing_control, tokens.spacing_control * 0.5);
    style.spacing.interact_size = egui::vec2(tokens.target_minimum, tokens.target_minimum);
    for font in style.text_styles.values_mut() { font.size *= text_scale; }
    style.visuals = egui_theme.default_visuals();
    style.visuals.panel_fill = tokens.background;
    style.visuals.override_text_color = Some(tokens.text_primary);
    style.visuals.selection.bg_fill = tokens.action;
    style.visuals.selection.stroke = egui::Stroke::new(tokens.focus_width, tokens.focus);
    ctx.set_style_of(egui_theme, style);
}

fn apply_scaled_style(ctx: &egui::Context, theme: ThemeMode, density: Density, text_scale: f32) {
    match theme {
        ThemeMode::Light => install_style(ctx, egui::Theme::Light, ThemeMode::Light, density, text_scale),
        ThemeMode::Dark => install_style(ctx, egui::Theme::Dark, ThemeMode::Dark, density, text_scale),
        ThemeMode::System => {
            install_style(ctx, egui::Theme::Light, ThemeMode::Light, density, text_scale);
            install_style(ctx, egui::Theme::Dark, ThemeMode::Dark, density, text_scale);
        }
    }
    let preference = match theme {
        ThemeMode::Light => egui::ThemePreference::Light,
        ThemeMode::Dark => egui::ThemePreference::Dark,
        ThemeMode::System => egui::ThemePreference::System,
    };
    ctx.set_theme(preference);
}

pub fn apply_style(ctx: &egui::Context, theme: ThemeMode, density: Density) {
    apply_scaled_style(ctx, theme, density, 1.0);
}

pub fn apply_capabilities(ctx: &egui::Context, capabilities: &RuntimeCapabilities) -> Result<(), CapabilityError> {
    capabilities.validate()?;
    apply_scaled_style(ctx, capabilities.theme, capabilities.density, capabilities.text_scale);
    Ok(())
}

pub fn app_frame<R>(ui: &mut egui::Ui, capabilities: &RuntimeCapabilities, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> Result<egui::InnerResponse<R>, CapabilityError> {
    apply_capabilities(ui.ctx(), capabilities)?;
    Ok(egui::CentralPanel::default().show(ui, add_contents))
}

pub fn button(ui: &mut egui::Ui, label: impl Into<egui::WidgetText>, intent: ButtonIntent, disabled: bool) -> egui::Response {
    let tokens = Tokens::for_theme(if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light }, Density::Comfortable);
    let (fill, text) = match intent {
        ButtonIntent::Primary => (tokens.action, tokens.on_action),
        ButtonIntent::Secondary => (tokens.card, tokens.text_primary),
        ButtonIntent::Ghost => (egui::Color32::TRANSPARENT, tokens.text_primary),
        ButtonIntent::Destructive => (tokens.destructive, tokens.on_destructive),
    };
    ui.add_enabled(!disabled, egui::Button::new(label).fill(fill).stroke(egui::Stroke::new(1.0, text)).min_size(ui.spacing().interact_size))
}

pub fn icon_button(ui: &mut egui::Ui, accessible_label: &str, glyph: &str, disabled: bool) -> egui::Response {
    let response = ui.add_enabled(!disabled, egui::Button::new(glyph).min_size(ui.spacing().interact_size));
    response.widget_info(|| egui::WidgetInfo::labeled(egui::WidgetType::Button, !disabled, accessible_label));
    response.on_hover_text(accessible_label)
}

pub fn toolbar<R>(ui: &mut egui::Ui, vertical: bool, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<R> {
    if vertical { ui.vertical(add_contents) } else { ui.horizontal(add_contents) }
}

pub fn tabs(ui: &mut egui::Ui, selected: &mut usize, labels: &[&str]) -> Vec<egui::Response> {
    let mut responses = Vec::with_capacity(labels.len());
    ui.horizontal(|ui| for (index, label) in labels.iter().enumerate() {
        let response = ui.selectable_label(*selected == index, *label);
        if response.clicked() { *selected = index; }
        responses.push(response);
    });
    responses
}

pub fn menu<R>(ui: &mut egui::Ui, label: &str, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<Option<R>> {
    ui.menu_button(label, add_contents)
}

pub fn dialog<R>(ctx: &egui::Context, open: &mut bool, title: &str, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> Option<egui::InnerResponse<Option<R>>> {
    egui::Window::new(title).open(open).collapsible(false).show(ctx, add_contents)
}

pub fn field(ui: &mut egui::Ui, label: &str, value: &mut String, error: Option<&str>) -> egui::InnerResponse<egui::Response> {
    ui.vertical(|ui| {
        ui.label(label);
        let response = ui.add(egui::TextEdit::singleline(value).hint_text(label));
        if let Some(message) = error {
            let theme = if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light };
            ui.colored_label(Tokens::for_theme(theme, Density::Comfortable).destructive, message);
        }
        response
    })
}

pub fn checkbox(ui: &mut egui::Ui, checked: &mut bool, label: &str) -> egui::Response { ui.checkbox(checked, label) }

pub fn list_row(ui: &mut egui::Ui, selected: &mut bool, label: &str) -> egui::Response {
    let response = ui.selectable_label(*selected, label);
    if response.clicked() { *selected = !*selected; }
    response
}

pub fn split_pane<R>(ui: &mut egui::Ui, primary: impl FnOnce(&mut egui::Ui) -> R, secondary: impl FnOnce(&mut egui::Ui) -> R) {
    ui.columns(2, |columns| { primary(&mut columns[0]); secondary(&mut columns[1]); });
}

pub fn toast(ui: &mut egui::Ui, message: &str, is_error: bool) -> egui::Response {
    let tokens = Tokens::for_theme(if ui.visuals().dark_mode { ThemeMode::Dark } else { ThemeMode::Light }, Density::Comfortable);
    ui.colored_label(if is_error { tokens.destructive } else { tokens.text_primary }, message)
}

pub fn status_badge(ui: &mut egui::Ui, label: &str, is_error: bool) -> egui::Response { toast(ui, label, is_error) }

pub fn card<R>(ui: &mut egui::Ui, add_contents: impl FnOnce(&mut egui::Ui) -> R) -> egui::InnerResponse<R> {
    egui::Frame::group(ui.style()).show(ui, add_contents)
}

pub fn empty_state(ui: &mut egui::Ui, heading: &str, description: &str) -> egui::Response {
    ui.vertical_centered(|ui| { ui.heading(heading); ui.label(description) }).response
}
