// GENERATED by BrandBuilder gen_egui.py. Do not edit.
use crate::{Density, ThemeMode};

pub const LOGICAL_UNIT_TO_POINTS: f32 = 1.0f32;
pub const COMFORTABLE_DENSITY: f32 = 1.0;
pub const COMPACT_DENSITY: f32 = 0.82;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UnitTransformError { NonFinite, NonPositive }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Tokens {
    pub background: egui::Color32,
    pub card: egui::Color32,
    pub overlay: egui::Color32,
    pub text_primary: egui::Color32,
    pub text_muted: egui::Color32,
    pub action: egui::Color32,
    pub on_action: egui::Color32,
    pub destructive: egui::Color32,
    pub on_destructive: egui::Color32,
    pub focus: egui::Color32,
    pub target_minimum: f32,
    pub spacing_control: f32,
    pub spacing_component: f32,
    pub focus_width: f32,
}

impl Tokens {
    pub fn for_theme(theme: ThemeMode, density: Density) -> Self {
        let scale = density.multiplier();
        let mut value = match theme {
            ThemeMode::Light => Self {
            background: egui::Color32::from_rgb(255, 255, 255),
            card: egui::Color32::from_rgb(248, 248, 246),
            overlay: egui::Color32::from_rgb(255, 255, 255),
            text_primary: egui::Color32::from_rgb(0, 0, 0),
            text_muted: egui::Color32::from_rgb(11, 12, 13),
            action: egui::Color32::from_rgb(194, 64, 0),
            on_action: egui::Color32::from_rgb(255, 255, 255),
            destructive: egui::Color32::from_rgb(233, 80, 95),
            on_destructive: egui::Color32::from_rgb(0, 0, 0),
            focus: egui::Color32::from_rgb(11, 12, 13),
                target_minimum: 44.0f32,
                spacing_control: 12.0f32,
                spacing_component: 24.0f32,
                focus_width: 2.0f32,
            },
            ThemeMode::Dark | ThemeMode::System => Self {
            background: egui::Color32::from_rgb(11, 12, 13),
            card: egui::Color32::from_rgb(18, 20, 22),
            overlay: egui::Color32::from_rgb(9, 10, 11),
            text_primary: egui::Color32::from_rgb(255, 255, 255),
            text_muted: egui::Color32::from_rgb(255, 217, 0),
            action: egui::Color32::from_rgb(194, 64, 0),
            on_action: egui::Color32::from_rgb(255, 255, 255),
            destructive: egui::Color32::from_rgb(233, 80, 95),
            on_destructive: egui::Color32::from_rgb(0, 0, 0),
            focus: egui::Color32::from_rgb(255, 217, 0),
                target_minimum: 44.0f32,
                spacing_control: 12.0f32,
                spacing_component: 24.0f32,
                focus_width: 2.0f32,
            },
        };
        // Density changes spacing, never the WCAG interaction-target floor.
        value.target_minimum = governed_points(value.target_minimum);
        value.spacing_control = governed_points(value.spacing_control) * scale;
        value.spacing_component = governed_points(value.spacing_component) * scale;
        value.focus_width = governed_points(value.focus_width);
        value
    }
}

pub fn logical_points(value: f32) -> Result<f32, UnitTransformError> {
    if !value.is_finite() { return Err(UnitTransformError::NonFinite); }
    let points = value * LOGICAL_UNIT_TO_POINTS;
    if !points.is_finite() { return Err(UnitTransformError::NonFinite); }
    if points <= 0.0 { return Err(UnitTransformError::NonPositive); }
    Ok(points)
}

fn governed_points(value: f32) -> f32 {
    logical_points(value).expect("governed Interface Canon measurements must be finite and positive")
}
