// GENERATED by shruggie-brandbuilder. Fonts come from bundled/npm sources,
// never a build-time network fetch.
import { GeistSans } from "geist/font/sans"
import { GeistMono } from "geist/font/mono"
import { Space_Grotesk } from "next/font/google"

export const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
})

// Geist ships 400 and 500 only. Geist Mono ships 400 only.
// Requesting a weight that does not exist makes the renderer synthesise a faux
// bold, which prints badly and forces outlined glyphs into PDFs.
export const fontVariables = [
  GeistSans.variable,
  GeistMono.variable,
  spaceGrotesk.variable,
].join(" ")

export { GeistSans, GeistMono }
