// GENERATED by shruggie-brandbuilder.
export function OpenGraphImage({ className }: { className?: string }) {
  return (
    <img
      className={className}
      src="/glitchpad-social-preview-1280.png"
      alt="Glitchpad, Cross-platform file viewer and editor"
    />
  )
}
